### ISSUE TITLE
Make the state structs accessible directly from C.

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/rocRAND#21]
You can take a look at CUDA headers and you'll see that state is designed as a struct: https://github.com/Geof23/Gklee/blob/master/Gklee/include/cuda/curand_mtgp32.h#L194

[rocRAND however has its state defined as a class with member functions](https://github.com/ROCmSoftwarePlatform/rocRAND/blob/master/library/include/rocrand_mtgp32.h#L158). This is not supported in C and thus it's not possible to obtain C style linkage. 

Why is this important? Many deep learning frameworks interface with Python and C via Python C Extensions.

I suggest two possible solutions would be either

1) Add a constructor to the mtgp32_engine class that takes in a hiprandStateMtgp32 object, allowing conversions from hiprandStateMtgp32 to mtgp32_engine.

OR

2) Change the mtgp32_engine class to a C style struct by removing the constructors & member functions, and instead make these free functions (i.e. global scope).

**Comment by jszuppe** [comment]
As far as I know name mangling applies to C++ (which has namespaces, overloading etc.), not to C, I guess you meant disabling name mangling. I think I know what is the basic requirement here. You want to be able to compile `hipandMakeMTGP32KernelState` and `hiprandMakeMTGP32Constants` functions in C, right?

> Thus, you'll be able to apply extern C and obtain C style linkage.

Yes, I guess user can add `extern "C"` around `#include curand_mtgp32_host.h`.

> Why is this important? Many deep learning frameworks interface with Python and C via Python C Extensions.

Can you provide test case or a link to a library which does that?

> Add a constructor to the mtgp32_engine class that takes in a hiprandStateMtgp32 object, allowing conversions from hiprandStateMtgp32 to mtgp32_engine.

You can notice that in rocRAND/hipRAND there is no `hiprandStateMtgp32`, there is only `hiprandStateMtgp32_t` (and that is true for every state). 

There are two reasons behind this:  1. you can't write `struct hiprandStateMtgp32` if `hiprandStateMtgp32` is an alias. hipRAND is a wrapper for cuRAND and rocRAND and not using aliases (`typedef`s) is troublesome, 2. cuRAND uses `hiprandState<>_t` everywhere anyway. In other words, even if we adjust it to work in C only `hiprandStateMtgp32_t` will be available and you won't be able to write `struct hiprandStateMtgp32` (`struct hiprandStateMtgp32_t` would obviously be wrong too).

**Comment by jszuppe** [comment]
> You can take a look at CUDA headers and you'll see that state is designed as a struct.

Yes, but only `curandStateMtgp32` and `curandStatePhilox4_32_10` can be used in C API, because other states are declared in `curand_kernel.h` which has C++-style functions (overloading). I guess it's more like a coincident than a deliberate decision. Anyway, I guess it's needed for porting something, so it's not like you're writing your own code. We will look into that.

**Comment by Jorghi12** [comment]
@jszuppe Which version of the curand_kernel.h header are you looking at? curandStateMtgp32 and curandStatePhilox4_32_10 are not the only states that can be used in the C API.


curandStateXORWOW: https://github.com/cheichler/RemoteRendering/blob/master/inc/curand_kernel.h#L122

curandStateMRG32k3a:
https://github.com/cheichler/RemoteRendering/blob/master/inc/curand_kernel.h#L186

curandStateSobol32:
https://github.com/cheichler/RemoteRendering/blob/master/inc/curand_kernel.h#L209

curandStateScrambledSobol32:
https://github.com/cheichler/RemoteRendering/blob/master/inc/curand_kernel.h#L227

curandStateSobol64:
https://github.com/cheichler/RemoteRendering/blob/master/inc/curand_kernel.h#L245

etc etc etc

**Comment by jszuppe** [comment]
In that header you have functions like curand() that has multiple overloads. C compiler should complain about that.

**Comment by jszuppe** [comment]
If you have something like `void foo(curandStateXORWOW);` in your C API in header file, then you have to include `curand_kernel.h` in that header, so programs that uses that header knows what it is. That you can't do, because compilation errors. And that's what I meant when I said that only 2 state structs can be used in C. Also, at that point I didn't know how you want to use struct state in C. 

> So let me explain why the headers have C++ code :)

You can do something like `THC_API struct curandStateMtgp32* THCRandom_generatorStates(struct THCState* state);`, because `struct curandStateMtgp32` in that expression is at the same time a forward declaration. That's why you're right you can make it work in C API, but it has nothing to do with how `nvcc` works (especially because files that uses your library and C API don't have to be compiled with `nvcc`). btw. IIRC, `nvcc` treats C code like C++ code (unless that changed) when it's in `.cu` file. 

Like I said before, it [forward declaration of `hiprandStateMtgp32`] won't be possible with hipRAND, because we use typedefs and you can't forward declare a typedef (when the struct is not defined). We would need different solution (either replace typedefs with real structs, or different C/C++ magic).

**Comment by jszuppe** [comment]
Anyway, now that I know what you need I'll look into it and try to find for the simplest solution that will enable you to write `THC_API struct hiprandStateMtgp32 * THCRandom_generatorStates(struct THCState* state);` in C API header. It's possible that for now it will be limited to `hiprandStateMtgp32`.

**Comment by Jorghi12** [comment]
@jszuppe Thanks. Yeah I agree. The usage of typedefs makes forward declaring really difficult here. A good solution would require a spoonful of creativity : ) 

(And yeah NVCC will compile the host code using a C++ compiler, but since the header only had structs on host side, it would interleave nicely with C. This helps turn the opaque type hiprandStateMtgp32 into a real type.)

**Comment by jszuppe** [comment]
@Jorghi12 Can you try branch [fix_21_and_test](https://github.com/ROCmSoftwarePlatform/rocRAND/tree/fix_21_and_test)?

In `test/extra` you can see what works (you don't have to compile and run it if you don't want to). Anyway, `rand_kernel_lib.cpp` is compiled using `hcc` to a dynamic library, it has C API similar to what you have in pytorch. Then you can do `gcc test_rand_kernel_lib.c -Wl,-rpath,../../build/test/extra/ -L../../build/test/extra/ -lrand_kernel_lib -o test_rand_kernel_lib` and run `./test_rand_kernel_lib` to see that it works.

It also includes fixes for other issues, and that's why now you have to add `CXX=hcc` before `cmake ../.` (see https://github.com/ROCmSoftwarePlatform/rocRAND/tree/fix_21#build-and-install).

**Comment by Jorghi12** [comment]
@jszuppe Awesome! I'll give this a go.

**Comment by jszuppe** [comment]
When you confirm it works for you, I'll push this and other changes into `develop` branch. I hop to do a new release with ROCm 1.8.2.

**Comment by iotamudelta** [comment]
@jszuppe ROCm 1.8.2 would be a *great* target but unlikely unless you notify releng here about this. If it works, I'd be in favor since PyTorch depends on it. Thanks!

**Comment by iotamudelta** [comment]
@jszuppe just talked to releng. If you merge to master and let them know today that it is in, we can make the window.

**Comment by jszuppe** [comment]
@iotamudelta Ah, I didn't know ROCm 1.8.2 will be released so soon (this week?). I'm sure I won't be able to merge this into `master` today. I need to get confirmation from @Jorghi12 that it works, merge it to `develop`, run tests on ROCm and CUDA machines etc., it's almost 10pm in Poland.

**Comment by iotamudelta** [comment]
@jszuppe we are in the release candidates. what is a realistic time line for landing in master from your side? I can check if we can make it work.

**Comment by jszuppe** [comment]
I can do that tomorrow, before 2pm CEST. But most likely without #22. We also have plans to remove some very minor warnings on CUDA environment, that would also be excluded.

**Comment by iotamudelta** [comment]
#22 is not a blocker from what I can see. and thanks - will forward.

**Comment by iotamudelta** [comment]
@jszuppe wrote this earlier but it vanished - I've done some limited testing and w/ changes to my PyTorch it compiles w/ this rocRAND branch.

**Comment by Jorghi12** [comment]
@iotamudelta There's already a fix for the struct issue in this patch here: https://github.com/ROCmSoftwarePlatform/rocRAND/commit/b7b180ab3634c4ca0ad6b3eaeee60989d778365f. 

If you got it to run with this branch (fix_21_and_test), then let's have @jszuppe merge it since it passes tests.
