### ISSUE TITLE
__sincosf issue in rocrand_normal

### ISSUE THREAD

**Issue by bragadeesh** [ROCmSoftwarePlatform/rocRAND#43]
https://github.com/ROCmSoftwarePlatform/rocRAND/blob/master/library/include/rocrand_normal.h#L54

With recent changes to HIP, __sincosf is getting mapped to native device implementations for speed advantage at the expense of no precision guarantees; does rocrand provide mechanism to choose between fast vs accurate (example __sincosf vs sincosf) so user has some control? We are seeing accuracy issues due to this, and looking for recommendations

**Comment by ex-rzr** [comment]
No, rocRAND doesn't have such mechanism currently.

> We are seeing accuracy issues due to this, and looking for recommendations

Where are these accuracy issues: in rocRAND tests or in other programs/libraries that use rocRAND?

**Comment by bragadeesh** [comment]
thanks; we are looking into this as this is one of the suspected issues, we will update when we have more info

**Comment by VincentSC** [comment]
Ok, I've asked for a list of alike changes and once we received these we'll go through our projects to find usages. If we suspect accuracy problems, we'll create issues and tag you.

I will close the issue for now, as the accuracy (to a certain level) is not important for RNGs. Thank you for the speedup.

**Comment by VincentSC** [comment]
Question about how to know which functions are future-proof.

So the old `sincosf` is removed, the current `__sincosf` moves `sincosf`, and a new native implementation is put for `__sincosf`?

I understood more functions are being made native, but these seem to get `_native` in the function name. How is decided when a new function is added like [`__ocml_cos_f32` - > `__ocml_native_cos_f32`](https://github.com/ROCm-Developer-Tools/HIP/pull/864/files#diff-28f7770548ea2af436ce25feac93625a) and when is it like here? Is this because [OCML](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/doc/OCML.md) functions always have to start with `__`? Now I'm not sure if a function starting with `__` can potentially be made less accurate in the future. Could you explain? Should we add unit-tests to check for accuracy? Is there a planning document of native functions that are targeted with some info on performance and accuracy?

**Comment by arsenm** [comment]
I have been thinking of OCML as a language internal implementation library without a fully stable API (hence the __ prefix). I did a cleanup a while ago since there was a naming inconsistency mess with some of the builtins, so now the _native_ ones should be equivalent to the OpenCL versions, but IIRC there wasn't actually a change in behavior. Not sure what's going on in HIP. Public API functions definitely should not start with __.

**Comment by b-sumner** [comment]
OCML is an internal library to be used by language runtimes so I think we should take it out of this discussion.  What should be talking about here are the differences between HIP/Cuda  __function vs function, e.g. __sincosf vs. sincosf.  Those differences are documented, at least in the Cuda documentation, and it says that the accuracy provided by the __ variants is lower and the domain may be reduced, to permit faster execution.  Our first implementation of the __ variants did not provide better performance (and reduced accuracy) but we have corrected that.  I can certainly see how this could have misled developers in the past, but in general developers should be prepared to regularly test the __ variants as their accuracy can change from release to release and from device to device.

**Comment by VincentSC** [comment]
Ok, I follow how OCML is positioned here. Thanks Matt.

My experience with __ functions is that they are always faster, but sometimes less accurate and sometimes only i.e. not IEEE-compliant like denorms.

Not sure if we can take that responsibility, as we'll probably find out by accident if such change arrives. This means a bug could get in without us knowing, or that a potential performance upgrade could be left out without knowing. Could the HIP-team therefore start profiding a CHANGELOG.md that includes this kinds of changes? Please?
