### ISSUE TITLE
Add topics `sobol`, `sobol-sequence`

### ISSUE THREAD

**Issue by Beliavsky** [ROCmSoftwarePlatform/rocRAND#478]
I suggest adding the topics `sobol`, `sobol-sequence` in the About section since the project implements the Sobol sequence.

**Comment by ppanchad-amd** [comment]
@Beliavsky Internal ticket has been created to add these topics. Thanks!

**Comment by stanleytsang-amd** [comment]
Sorry for the delay in response - perhaps the issue was valid back in April, but my current observations don't seem to indicate any deficiency on our documentation of the sobol generators.  See my comments below:

@Beliavsky Can you clarify exactly where you're referring to?  The sobol generators are well-documented in our [documentation ](https://rocm.docs.amd.com/projects/rocRAND/en/latest/conceptual/programmers-guide.html#programmers-guide).  The "About" section in the documentation contains legal information and does not mention any of the RNG types.  Are you referring to the "About" section in the top right corner of the repo home page that currently says "RAND library for HIP programming language"?  If so, then no, I don't think that's a good place for it, it's meant to be a very short one-liner summary of the purpose of the rocRAND library.
